#!/usr/bin/env bash
# init.sh -- Initialization agent for long-running projects.
#
# Run once at the start of the first session. Generates:
#   - feature_list.json (from features.txt)
#   - claude-progress.txt (progress log header)
#   - AGENT_PROMPT.md (prompt for the coding agent)
#   - current_tasks/ (task lock directory)
#   - agent_logs/ (log output for long-run.sh)
#   - initial git commit
#
# Existing files are not overwritten by default. Only feature_list.json
# is regenerated by generate_features.py, which preserves passes flags.
#
# Usage:
#   ./init.sh                # Target the current directory
#   ./init.sh /path/to/proj  # Target a specific directory

set -euo pipefail

ROOT_DIR="${1:-.}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON="${PYTHON:-python3}"

mkdir -p "$ROOT_DIR"
cd "$ROOT_DIR"

echo "=== Initializing long-running project ==="
echo "Target directory: $(pwd)"

# [0/5] Copy helper scripts to ROOT_DIR (allow SCRIPT_DIR != ROOT_DIR for worktrees)
if [ "$SCRIPT_DIR" != "$(pwd)" ]; then
    for helper in generate_features.py next_feature.py mark_passed.py update_progress.sh; do
        if [ ! -f "$helper" ]; then
            cp "$SCRIPT_DIR/$helper" "$helper"
            chmod +x "$helper"
        fi
    done
    echo "[0/5] Placed helper scripts"
fi

# [1/5] Check git repository (supports worktree .git files)
if ! git rev-parse --git-dir >/dev/null 2>&1; then
    echo "[1/5] Initializing git repository"
    git init -q
else
    echo "[1/5] Using existing git repository"
fi

# [2/5] features.txt and feature_list.json
if [ ! -f features.txt ]; then
    echo "[2/5] Creating features.txt template (features.txt not found)"
    cat > features.txt <<'EOF'
# functional: User can log in
- Open the login form
- Enter email and password
- Click the login button
- Verify redirect to dashboard

# functional: User can log out
- Click the logout button
- Verify the session is destroyed
- Verify redirect to login page
EOF
fi
echo "[2/5] Generating feature_list.json via generate_features.py"
"$PYTHON" "$SCRIPT_DIR/generate_features.py" features.txt feature_list.json

# [3/5] claude-progress.txt
if [ ! -f claude-progress.txt ]; then
    echo "[3/5] Initializing claude-progress.txt"
    cat > claude-progress.txt <<'EOF'
# Long-Running Project Progress Log

This file is updated automatically by update_progress.sh.
Each entry includes: timestamp / completed work / commit / next steps.
EOF
else
    echo "[3/5] Using existing claude-progress.txt"
fi

# [4/5] AGENT_PROMPT.md and work directories
if [ ! -f AGENT_PROMPT.md ]; then
    echo "[4/5] Creating AGENT_PROMPT.md"
    cat > AGENT_PROMPT.md <<'EOF'
You are a coding agent for a long-running project.

## Session Workflow

1. Run `tail -20 claude-progress.txt` to review previous work
2. Run `git log --oneline -10` to check recent commits
3. Run `python3 next_feature.py` to get the highest-priority incomplete feature
4. Implement that single feature. Do not work on multiple features at once
5. Run tests and verify they pass
6. `git add -A && git commit -m "feat: <feature description>"`
7. `python3 mark_passed.py "<feature description>"` to record completion
8. `./update_progress.sh "<completed work>" "<next steps>"` to update the progress log

## Rules

- One feature per session. Do not move on even if context remains
- Never commit with failing tests
- Do not modify steps or description in feature_list.json
  (only the passes flag should change)
- If anything is unclear, write it in NOTES.md for the next session
EOF
else
    echo "[4/5] Using existing AGENT_PROMPT.md"
fi
mkdir -p current_tasks agent_logs

# [5/5] Initial commit (uses current git config)
if [ -z "$(git log --oneline 2>/dev/null || true)" ]; then
    echo "[5/5] Creating initial commit"
    git add features.txt feature_list.json claude-progress.txt AGENT_PROMPT.md
    if git commit -q -m "chore: initialize long-running agent harness"; then
        echo "      Initial commit created"
    else
        echo "      WARNING: Initial commit failed." >&2
        echo "      Set git config user.name / user.email and" >&2
        echo "      run git commit manually." >&2
    fi
else
    echo "[5/5] Commit history exists. Skipping initial commit"
fi

echo "=== Initialization complete ==="
echo
echo "Start loop execution with AGENT_PROMPT.md in the next session:"
echo "  ./long-run.sh"
